name: Trendify
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
    
  shared_preferences: ^2.5.2
  jwt_decoder:  ^2.0.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.3.0
  flutter_stripe: ^11.4.0
  cached_network_image: ^3.2.1
  flutter_rating_bar: ^4.0.1
  googleapis: ^13.2.0
  google_fonts: ^6.2.1
  rive: ^0.13.20
  readmore: ^3.0.0
  firebase_core: ^2.18.0
  firebase_auth: ^4.11.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/trend.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/trend.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/trend.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
